name: notify-trigger

on:
  schedule:
    - cron:  '00 11 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for 'tock-tbf' updates
        run: |
          TARGET_FILE="tock-tbf/src"
          
          RESPONSE=$(curl -s "https://api.github.com/repos/ioqnq/KevinCookieCompany.com/commits?path=$TARGET_FILE&sha=main")
          
          COMMIT_SHA=$(echo "$RESPONSE" | jq -r ".[0].sha")
          
          echo "Commit sha: $COMMIT_SHA"

