name: Notify
on:
  workflow_run:
    workflows: ["notify-trigger"]
    types: [completed]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      issues: write
      contents: read
    steps:
      - name: Create issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            previous_issue_name=$(gh issue list \
              --label "$LABELS" \
              --json title \
              --jq '.[0].title')
            if [[ -n $previous_issue_number && $previous_issue_name == "$TITLE" ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Bring updates from 'tock-tbf' to 'tbf-parser'
          ASSIGNEES: unassigned
          LABELS: D3-TBF PARSER,P1-CRITICAL
          BODY: |
            After finishing #41 , use the resulting information to update out library to be up-to-date w/r/t to features with upstream crate. Note that it is still necessary that we do not use static lifetimes.
          PINNED: false
          CLOSE_PREVIOUS: false
