name: notify-trigger

on:
  schedule:
    - cron:  '0/30 * * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: chmod +x .github/workflows/isUpdated.sh
