name: notify-trigger

on:
  schedule:
    - cron:  '00 11 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: isUpdated.sh
