name: Notify
on:
  workflow_run:
    workflows: ["notify-trigger"]
    types: [completed]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      issues: write
      contents: read
    steps:
      - name: Create issue
        run: |
          mapfile -t matching_issues < <(gh issue list \
            --label "$LABELS" \
            --state open \
            --json number,title \
            --jq ".[] | select(.title == \"$TITLE\") | .number")
          
          for issue_number in "${matching_issues[@]}"; do
            echo "Closing and unpinning issue #$issue_number with matching title"
            gh issue close "$issue_number"
            gh issue unpin "$issue_number" || echo "(Not pinned)"
          done
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Bring updates from 'tock-tbf' to 'tbf-parser'
          ASSIGNEES: unassigned
          LABELS: D3-TBF PARSER,P1-CRITICAL
          BODY: |
            After finishing #41 , use the resulting information to update out library to be up-to-date w/r/t to features with upstream crate. Note that it is still necessary that we do not use static lifetimes.
          PINNED: false
          CLOSE_PREVIOUS: true
