name: sha-checker

on:
  pull_request:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
      - name: List all changed files
        run: |
          # Check if PR contains our label
          # if [[  != 'EXCLUSIVE LABEL' ]]; then
          #   echo PR doesn't contain label => don't run
          #   exit 0
          # fi
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      # - name: Check if sha is included in PR changes
      #   run: |
          
        
          
