name: sha-checker

on:
  pull_request:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check if files included in PR
        run: |
          # Get PR number
          PR_NO=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR number: $PR_NO"
          
          # Get PR labels
          labels="$(gh api repos/ioqnq/KevinCookiedownstream/pulls/$PR_NO --jq '.labels.[].name')"
          echo "$labels"

          # Get changed files
          gh pr view "$PR_NO" --json files -q '.files[].path'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Check if sha is included in PR changes
      #   run: |
          
        
          
